openapi: 3.1.0
info:
  title: Mask System API
  description: API documentation for the Mask System
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

# 路徑和組件將由其他文件提供 